//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdTryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int Customer_ID { get; set; }
        public string Cname { get; set; }
        public string Ccity { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Salesman_ID { get; set; }
    
        public virtual tblSalesman tblSalesman { get; set; }
    }
}
